import { createSlice } from "@reduxjs/toolkit";

export const wosSlice = createSlice({
  name: "bi_wos",
  initialState: {
    channel: [],
    calendarDealer: {
      "ALKOSTO": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": "Abril es una ganga",
          "W15": "Abril es una ganga",
          "W16": "Abril es una ganga",
          "W17": "Abril es una ganga",
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": "Agosto Alkosto",
          "W32": "Agosto Alkosto",
          "W33": "Agosto Alkosto",
          "W34": "Agosto Alkosto",
          "W35": "Agosto Alkosto",
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "EXITO": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": "Dias Espaciales",
          "W09": "Dias Espaciales",
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": "Megaprima",
          "W27": "Megaprima",
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": "Dias Espaciales",
          "W40": "Dias Espaciales",
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "FALABELLA": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "HOMECENTER": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "JUMBO": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "OLIMPICA": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "AGAVAL": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "ANTIOQUIA": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "FLAMINGO": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "HOGAR Y MODA": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "MULTIELECTRO": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "CENTRO": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "HICEL": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "INNOVAR": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "SED": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "EJE_CAFETERO": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "LAGOBO": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "SUPERMERCADOS MERCACENTRO": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "MEICO": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "OTHERS_COSTA": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "ALCA": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "COMERCIALIZADORA BEST BUY S.A.S.": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "COOMULTRASAN": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "HVC": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "SANTANDERES": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "ELECTROJAPONESA": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "JL Y RB S.A.S.": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "VALLE": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": null,
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": null,
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": null,
          "W49": null,
          "W50": null,
          "W51": null,
          "W52": null
      },
      "ALL": {
          "W01": null,
          "W02": null,
          "W03": null,
          "W04": null,
          "W05": null,
          "W06": null,
          "W07": null,
          "W08": null,
          "W09": null,
          "W10": null,
          "W11": null,
          "W12": null,
          "W13": null,
          "W14": null,
          "W15": null,
          "W16": null,
          "W17": null,
          "W18": null,
          "W19": "Día de la madre ",
          "W20": null,
          "W21": null,
          "W22": null,
          "W23": null,
          "W24": "Día del Padre ",
          "W25": null,
          "W26": null,
          "W27": null,
          "W28": null,
          "W29": null,
          "W30": null,
          "W31": null,
          "W32": null,
          "W33": null,
          "W34": null,
          "W35": null,
          "W36": null,
          "W37": null,
          "W38": null,
          "W39": null,
          "W40": null,
          "W41": null,
          "W42": null,
          "W43": null,
          "W44": null,
          "W45": null,
          "W46": null,
          "W47": null,
          "W48": "Black Friday",
          "W49": "Navidad",
          "W50": "Navidad",
          "W51": null,
          "W52": null
      }
    },
    dealerTable: ['ALL DEALER'],
    channelSelectedMJ: [],
    dealer: [],
    dealerSelected:[],
    dealerSelectedMJ: [],
    isLoading: false,
    isLoadingAllDealers: true,
    isLoadingDownDealersTable: false,
    filter_bi: {},
    filters: {},
    pg: [],
    pg_tool: [],
    pg2:[],
    status: [],
    ar:[],
    km: ["SI", "NO"],
    year:[],
    regional:[],
    majorCostmr:[],
    table_cpsi:{
      data: []
    },
    titulosFirstTable: [
      "P |PM|",
      "P |KAM|",
      "P |Y-1|",
      "S |R+F|",
      "S |Y-1|",
      "S |R+F| USD",
      "S |Y-1| USD",
      "USD ∆ VS Y-1",
      "S |R+F| COP",
      "S |Y-1| COP",
      "COP ∆ VS Y-1",
      "S FCST W-1",
      "AR% FCST W-1",
      "SELLABLE INV",
      "DISPLAY INV",
      "WOS-4 |QTY|",
      "WOS+8 |QTY|",
      "WOS-4 |AMT|",
      "WOS+8 |AMT|",
    ],
    table_MeasureGral:{
      data: []
    },
    table_cpsi2Gral:{
      data: []
    },
    table_NewCPSI:{
      data: []
    },
    table_NewCPSIView:{
      data: []
    },
    table_NewMeasure:{
      data: []
    },
    table_NewCpsiFilterDealer:{
      data: []
    },
  },
  reducers: {
    setChannel: (state, { payload }) => {
      state.channel = payload;
    },
    setDealer: (state, { payload }) => {
      state.dealer = payload;
    },
    setPg: (state, { payload }) => {
      state.pg = payload;
    },
    setPg_Tool: (state, { payload }) => {
      state.pg_tool = payload;
    },
    setPg_2: (state, { payload }) => {
      state.pg2 = payload;
    },
    setStatus: (state, { payload }) => {
      state.status = payload;
    },
    setAprovedRef: (state, { payload }) => {
      state.ar = payload;
    },
    setKeyModels: (state, { payload }) => {
      state.km = payload;
    },
    setYear: (state, { payload }) => {
      state.year = payload;
    },
    setRegional: (state, { payload }) => {
      state.regional = payload;
    },
    setMajorCostmr: (state, { payload }) => {
      state.majorCostmr = payload;
    },
    changeLoading: (state, { payload }) => {
      state.isLoading = payload;
    },
    changingLoadingAllDealers: (state, { payload }) => {
      state.isLoadingAllDealers = payload;
    },
    changingLoadingDownDealersTable: (state, { payload }) => {
      state.isLoadingDownDealersTable = payload;
    },
    setFilterWos: (state, { payload }) => {
      state.filters = payload
    },
    setChannelpsi: ( state, {payload}) => {
      state.table_cpsi = payload
    },
    setMeasureGeneral: ( state, {payload}) => {
      state.table_MeasureGral = payload
    },
    setTableCPSIGral: ( state, {payload}) => {
      state.table_cpsi2Gral = payload
    },
    setTableNewCPSI: ( state, {payload}) => {
      state.table_NewCPSI = payload
    },
    setTableNewCPSIView: ( state, {payload}) => {
      state.table_NewCPSIView = payload
    },
    setTableNewMeasure: ( state, {payload}) => {
      state.table_NewMeasure = payload
    },
    setTableCpsiFilterDealer: ( state, {payload}) => {
      state.table_NewCpsiFilterDealer = payload
    },
    setDealerSelected: ( state, {payload}) => {
      state.dealerSelected = payload
    },
    setStateGeneral: ( state , {payload} ) => {
      Object.assign(state, payload)
    },
    settitulosFirstTable: (state , {payload}) => {
      // // state.titulosFirstTable = payload
      // let names = []
      // for (let  dealer in Object.keys(payload)) {
      //   names = [
      //     ...names,
      //     ...state.titulosFirstTable
      //   ]
      //   state.dealerTable = [
      //     ...state.dealerTable,
      //     Object.keys(payload)[dealer]
      //   ]
      // }

      // state.titulosFirstTable = names
    },
    setDealerSelectedMJ: ( state, {payload}) => {
      state.dealerSelectedMJ = payload
    },
    setChannelSelectedMJ: ( state, {payload}) => {
      state.channelSelectedMJ = payload
    }
  },
});

// Action creators are generated for each case reducer function
export const {
  changeLoading,
  changingLoadingAllDealers,
  changingLoadingDownDealersTable,
  setFilterWos,
  setChannel,
  setDealer,
  setPg,
  setPg_Tool,
  setPg_2,
  setStatus,
  setAprovedRef,
  setKeyModels,
  setYear,
  setRegional,
  setMajorCostmr,
  setChannelpsi,
  setMeasureGeneral,
  setTableCPSIGral,
  setTableNewCPSI,
  setTableNewCPSIView,
  setTableNewMeasure,
  setTableCpsiFilterDealer,
  setDealerSelected,
  settitulosFirstTable,
  setStateGeneral,
  setDealerSelectedMJ,
  setChannelSelectedMJ
} = wosSlice.actions;
